-- ============================================================
-- BANCO DE DADOS: SISTEMA DE RESERVAS DE HOTEL
-- PostgreSQL
-- Conteúdo: tabelas, dados (>100 registros), procedures e triggers
-- ============================================================

-- Sugestão de uso no terminal:
-- createdb hotel_triggers
-- psql -d hotel_triggers -f banco_hotel_triggers_procedures.sql
--
-- Ou dentro do psql:
-- CREATE DATABASE hotel_triggers;
-- \c hotel_triggers
-- \i /caminho/banco_hotel_triggers_procedures.sql

DROP TABLE IF EXISTS notificacao CASCADE;
DROP TABLE IF EXISTS auditoria_reserva CASCADE;
DROP TABLE IF EXISTS reserva CASCADE;
DROP TABLE IF EXISTS quarto CASCADE;
DROP TABLE IF EXISTS hospede CASCADE;
DROP TABLE IF EXISTS tipo_quarto CASCADE;
DROP TABLE IF EXISTS funcionario CASCADE;

DROP FUNCTION IF EXISTS fn_validar_reserva() CASCADE;
DROP FUNCTION IF EXISTS fn_auditar_reserva() CASCADE;
DROP FUNCTION IF EXISTS fn_notificar_cancelamento() CASCADE;

DROP PROCEDURE IF EXISTS sp_criar_reserva(INTEGER, INTEGER, DATE, DATE, INTEGER);
DROP PROCEDURE IF EXISTS sp_cancelar_reserva(BIGINT, TEXT);
DROP PROCEDURE IF EXISTS sp_reajustar_diarias(NUMERIC, INTEGER);

CREATE TABLE tipo_quarto (
    id_tipo INTEGER PRIMARY KEY,
    nome_tipo VARCHAR(50) NOT NULL UNIQUE,
    valor_diaria NUMERIC(10,2) NOT NULL CHECK (valor_diaria > 0),
    capacidade INTEGER NOT NULL CHECK (capacidade > 0),
    descricao VARCHAR(200)
);

CREATE TABLE quarto (
    id_quarto INTEGER PRIMARY KEY,
    numero VARCHAR(10) NOT NULL UNIQUE,
    andar INTEGER NOT NULL CHECK (andar > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('Disponível', 'Ocupado', 'Manutenção', 'Inativo')),
    vista VARCHAR(30),
    id_tipo INTEGER NOT NULL REFERENCES tipo_quarto(id_tipo)
);

CREATE TABLE hospede (
    id_hospede INTEGER PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    cidade VARCHAR(80),
    estado CHAR(2),
    telefone VARCHAR(20)
);

CREATE TABLE reserva (
    id_reserva BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospede INTEGER NOT NULL REFERENCES hospede(id_hospede),
    id_quarto INTEGER NOT NULL REFERENCES quarto(id_quarto),
    data_checkin DATE NOT NULL,
    data_checkout DATE NOT NULL,
    quantidade_hospedes INTEGER NOT NULL CHECK (quantidade_hospedes > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('Confirmada', 'Hospedada', 'Concluída', 'Cancelada')),
    valor_total NUMERIC(10,2),
    criada_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (data_checkout > data_checkin)
);

CREATE TABLE auditoria_reserva (
    id_auditoria BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_reserva BIGINT,
    operacao VARCHAR(20) NOT NULL,
    status_anterior VARCHAR(20),
    status_novo VARCHAR(20),
    valor_anterior NUMERIC(10,2),
    valor_novo NUMERIC(10,2),
    descricao TEXT,
    data_evento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notificacao (
    id_notificacao BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_reserva BIGINT,
    mensagem TEXT NOT NULL,
    criada_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processada BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE funcionario (
    id_funcionario INTEGER PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cargo VARCHAR(60) NOT NULL,
    salario NUMERIC(10,2) NOT NULL CHECK (salario > 0),
    id_supervisor INTEGER REFERENCES funcionario(id_funcionario)
);

INSERT INTO tipo_quarto
(id_tipo, nome_tipo, valor_diaria, capacidade, descricao)
VALUES
(1, 'Standard', 180.00, 2, 'Quarto econômico para até duas pessoas'),
(2, 'Superior', 260.00, 3, 'Quarto intermediário com espaço adicional'),
(3, 'Luxo', 420.00, 2, 'Quarto de alto padrão com vista privilegiada'),
(4, 'Família', 520.00, 5, 'Quarto amplo para famílias'),
(5, 'Presidencial', 1200.00, 4, 'Suíte premium com sala privativa'),
(6, 'Executivo', 350.00, 2, 'Categoria voltada a viagens corporativas');

INSERT INTO quarto
(id_quarto, numero, andar, status, vista, id_tipo)
VALUES
(1, '101', 1, 'Disponível', 'Jardim', 1),
(2, '102', 1, 'Disponível', 'Jardim', 1),
(3, '103', 1, 'Ocupado', 'Piscina', 1),
(4, '104', 1, 'Disponível', 'Cidade', 1),
(5, '105', 1, 'Disponível', 'Cidade', 1),
(6, '201', 2, 'Disponível', 'Cidade', 2),
(7, '202', 2, 'Manutenção', 'Jardim', 2),
(8, '203', 2, 'Disponível', NULL, 2),
(9, '204', 2, 'Disponível', 'Jardim', 2),
(10, '205', 2, 'Disponível', NULL, 2),
(11, '301', 3, 'Disponível', 'Mar', 3),
(12, '302', 3, 'Ocupado', 'Jardim', 3),
(13, '303', 3, 'Disponível', 'Jardim', 3),
(14, '304', 3, 'Manutenção', 'Jardim', 3),
(15, '305', 3, 'Disponível', 'Cidade', 3),
(16, '401', 4, 'Disponível', 'Cidade', 4),
(17, '402', 4, 'Disponível', NULL, 4),
(18, '403', 4, 'Ocupado', NULL, 4),
(19, '404', 4, 'Disponível', 'Jardim', 4),
(20, '405', 4, 'Disponível', NULL, 4),
(21, '501', 5, 'Disponível', 'Cidade', 6),
(22, '502', 5, 'Manutenção', NULL, 6),
(23, '503', 5, 'Disponível', 'Mar', 6),
(24, '504', 5, 'Disponível', 'Cidade', 6),
(25, '505', 5, 'Disponível', 'Mar', 6),
(26, '601', 6, 'Disponível', NULL, 5),
(27, '602', 6, 'Ocupado', 'Piscina', 5),
(28, '603', 6, 'Disponível', 'Jardim', 3),
(29, '604', 6, 'Disponível', 'Cidade', 3),
(30, '605', 6, 'Disponível', 'Mar', 3);

INSERT INTO hospede
(id_hospede, nome, email, cidade, estado, telefone)
VALUES
(1, 'Ana Alves', 'ana.1@email.com', 'Londrina', 'PR', '44900000001'),
(2, 'Bruno Nunes', 'bruno.2@email.com', 'Maringá', 'PR', '44900000002'),
(3, 'Carla Ribeiro', 'carla.3@email.com', 'Apucarana', 'PR', '44900000003'),
(4, 'Diego Dias', 'diego.4@email.com', 'São Paulo', 'SP', '44900000004'),
(5, 'Elisa Freitas', 'elisa.5@email.com', 'Campinas', 'SP', '44900000005'),
(6, 'Fábio Pereira', 'fabio.6@email.com', 'Florianópolis', 'SC', '44900000006'),
(7, 'Gabriela Lima', 'gabriela.7@email.com', 'CURITIBA', 'SC', '44900000007'),
(8, 'Henrique Rocha', 'henrique.8@email.com', 'Rio de Janeiro', 'RJ', NULL),
(9, 'Isabela Costa', 'isabela.9@email.com', NULL, 'SP', '44900000009'),
(10, 'João Cardoso', 'joao.10@email.com', 'Curitiba', 'PR', '44900000010'),
(11, 'Karina Barros', 'karina.11@email.com', 'Londrina', 'PR', '44900000011'),
(12, 'Lucas Tavares', 'lucas.12@email.com', 'Maringá', 'PR', '44900000012'),
(13, 'Marina Gomes', 'marina.13@email.com', 'Apucarana', 'PR', '44900000013'),
(14, 'Nicolas Souza', 'nicolas.14@email.com', 'São Paulo', 'SP', '44900000014'),
(15, 'Olívia Melo', 'olivia.15@email.com', 'Campinas', 'SP', '44900000015'),
(16, 'Paulo Prado', 'paulo.16@email.com', 'Florianópolis', 'SC', NULL),
(17, 'Quitéria Ferreira', 'quiteria.17@email.com', 'Joinville', 'SC', '44900000017'),
(18, 'Rafael Moreira', 'rafael.18@email.com', 'Rio de Janeiro', 'RJ', '44900000018'),
(19, 'Sofia Oliveira', 'sofia.19@email.com', NULL, 'SP', '44900000019'),
(20, 'Tiago Martins', 'tiago.20@email.com', 'Curitiba', 'PR', '44900000020'),
(21, 'Ursula Alves', 'ursula.21@email.com', 'Londrina', 'PR', '44900000021'),
(22, 'Valter Nunes', 'valter.22@email.com', 'Maringá', 'PR', '44900000022'),
(23, 'Wagner Ribeiro', 'wagner.23@email.com', 'Apucarana', 'PR', '44900000023'),
(24, 'Yasmin Dias', 'yasmin.24@email.com', 'São Paulo', 'SP', NULL),
(25, 'Zeca Freitas', 'zeca.25@email.com', 'Campinas', 'SP', '44900000025'),
(26, 'Amanda Pereira', 'amanda.26@email.com', 'Florianópolis', 'SC', '44900000026'),
(27, 'Bianca Lima', 'bianca.27@email.com', 'Joinville', 'SC', '44900000027'),
(28, 'Caio Rocha', 'caio.28@email.com', 'Rio de Janeiro', 'RJ', '44900000028'),
(29, 'Daniela Costa', 'daniela.29@email.com', NULL, 'SP', '44900000029'),
(30, 'Eduardo Cardoso', 'eduardo.30@email.com', 'Curitiba', 'PR', '44900000030'),
(31, 'Fernanda Barros', 'fernanda.31@email.com', 'Londrina', 'PR', '44900000031'),
(32, 'Gustavo Tavares', 'gustavo.32@email.com', 'Maringá', 'PR', NULL),
(33, 'Helena Gomes', 'helena.33@email.com', 'Apucarana', 'PR', '44900000033'),
(34, 'Igor Souza', 'igor.34@email.com', 'São Paulo', 'SP', '44900000034'),
(35, 'Juliana Melo', 'juliana.35@email.com', 'Campinas', 'SP', '44900000035'),
(36, 'Leandro Prado', 'leandro.36@email.com', 'Florianópolis', 'SC', '44900000036'),
(37, 'Marta Ferreira', 'marta.37@email.com', 'Joinville', 'SC', '44900000037'),
(38, 'Natália Moreira', 'natalia.38@email.com', 'Rio de Janeiro', 'RJ', '44900000038'),
(39, 'Otávio Oliveira', 'otavio.39@email.com', NULL, 'SP', '44900000039'),
(40, 'Patrícia Martins', 'patricia.40@email.com', 'Curitiba', 'PR', NULL),
(41, 'Renata Alves', 'renata.41@email.com', 'Londrina', 'PR', '44900000041'),
(42, 'Samuel Nunes', 'samuel.42@email.com', 'Maringá', 'PR', '44900000042'),
(43, 'Tainá Ribeiro', 'taina.43@email.com', 'Apucarana', 'PR', '44900000043'),
(44, 'Vinícius Dias', 'vinicius.44@email.com', 'São Paulo', 'SP', '44900000044'),
(45, 'William Freitas', 'william.45@email.com', 'Campinas', 'SP', '44900000045');

INSERT INTO reserva
(id_reserva, id_hospede, id_quarto, data_checkin, data_checkout, quantidade_hospedes, status, valor_total)
VALUES
(1, 1, 1, '2026-01-05', '2026-01-06', 1, 'Concluída', 180.00),
(2, 2, 8, '2026-01-08', '2026-01-10', 2, 'Concluída', 520.00),
(3, 3, 15, '2026-01-11', '2026-01-14', 2, 'Hospedada', 1260.00),
(4, 4, 22, '2026-01-14', '2026-01-18', 2, 'Concluída', 1400.00),
(5, 5, 29, '2026-01-17', '2026-01-22', 2, 'Concluída', 2100.00),
(6, 6, 6, '2026-01-20', '2026-01-21', 1, 'Concluída', 260.00),
(7, 7, 13, '2026-01-23', '2026-01-25', 2, 'Cancelada', 840.00),
(8, 8, 20, '2026-01-26', '2026-01-29', 3, 'Confirmada', 1560.00),
(9, 9, 27, '2026-01-29', '2026-02-02', 4, 'Cancelada', 4800.00),
(10, 10, 4, '2026-02-01', '2026-02-06', 2, 'Confirmada', 900.00),
(11, 11, 11, '2026-02-04', '2026-02-05', 1, 'Concluída', 420.00),
(12, 12, 18, '2026-02-07', '2026-02-09', 2, 'Hospedada', 1040.00),
(13, 13, 25, '2026-02-10', '2026-02-13', 2, 'Concluída', 1050.00),
(14, 14, 2, '2026-02-13', '2026-02-17', 2, 'Confirmada', 720.00),
(15, 15, 9, '2026-02-16', '2026-02-21', 3, 'Cancelada', 1300.00),
(16, 16, 16, '2026-02-19', '2026-02-20', 1, 'Confirmada', 520.00),
(17, 17, 23, '2026-02-22', '2026-02-24', 2, 'Cancelada', 700.00),
(18, 18, 30, '2026-02-25', '2026-02-28', 2, 'Confirmada', 1260.00),
(19, 19, 7, '2026-02-28', '2026-03-04', 3, 'Confirmada', 1040.00),
(20, 20, 14, '2026-03-03', '2026-03-08', 2, 'Concluída', 2100.00),
(21, 21, 21, '2026-03-06', '2026-03-07', 1, 'Concluída', 350.00),
(22, 22, 28, '2026-03-09', '2026-03-11', 2, 'Concluída', 840.00),
(23, 23, 5, '2026-03-12', '2026-03-15', 2, 'Concluída', 540.00),
(24, 24, 12, '2026-03-15', '2026-03-19', 2, 'Concluída', 1680.00),
(25, 25, 19, '2026-03-18', '2026-03-23', 5, 'Concluída', 2600.00),
(26, 26, 26, '2026-03-21', '2026-03-22', 1, 'Concluída', 1200.00),
(27, 27, 3, '2026-03-24', '2026-03-26', 2, 'Confirmada', 360.00),
(28, 28, 10, '2026-03-27', '2026-03-30', 3, 'Concluída', 780.00),
(29, 29, 17, '2026-03-30', '2026-04-03', 4, 'Concluída', 2080.00),
(30, 30, 24, '2026-04-02', '2026-04-07', 2, 'Concluída', 1750.00),
(31, 31, 1, '2026-04-05', '2026-04-06', 1, 'Concluída', 180.00),
(32, 32, 8, '2026-04-08', '2026-04-10', 2, 'Hospedada', 520.00),
(33, 33, 15, '2026-04-11', '2026-04-14', 2, 'Confirmada', 1260.00),
(34, 34, 22, '2026-04-14', '2026-04-18', 2, 'Confirmada', 1400.00),
(35, 35, 29, '2026-04-17', '2026-04-22', 2, 'Concluída', 2100.00),
(36, 36, 6, '2026-04-20', '2026-04-21', 1, 'Confirmada', 260.00),
(37, 37, 13, '2026-04-23', '2026-04-25', 2, 'Concluída', 840.00),
(38, 38, 20, '2026-04-26', '2026-04-29', 3, 'Concluída', 1560.00),
(39, 39, 27, '2026-04-29', '2026-05-03', 4, 'Hospedada', 4800.00),
(40, 40, 4, '2026-05-02', '2026-05-07', 2, 'Confirmada', 900.00),
(41, 41, 11, '2026-05-05', '2026-05-06', 1, 'Confirmada', 420.00),
(42, 42, 18, '2026-05-08', '2026-05-10', 2, 'Confirmada', 1040.00),
(43, 1, 25, '2026-05-11', '2026-05-14', 2, 'Cancelada', 1050.00),
(44, 2, 2, '2026-05-14', '2026-05-18', 2, 'Confirmada', 720.00),
(45, 3, 9, '2026-05-17', '2026-05-22', 3, 'Concluída', 1300.00),
(46, 4, 16, '2026-05-20', '2026-05-21', 1, 'Concluída', 520.00),
(47, 5, 23, '2026-05-23', '2026-05-25', 2, 'Concluída', 700.00),
(48, 6, 30, '2026-05-26', '2026-05-29', 2, 'Concluída', 1260.00),
(49, 7, 7, '2026-05-29', '2026-06-02', 3, 'Concluída', 1040.00),
(50, 8, 14, '2026-06-01', '2026-06-06', 2, 'Hospedada', 2100.00),
(51, 9, 21, '2026-06-04', '2026-06-05', 1, 'Cancelada', 350.00),
(52, 10, 28, '2026-06-07', '2026-06-09', 2, 'Concluída', 840.00),
(53, 11, 5, '2026-06-10', '2026-06-13', 2, 'Confirmada', 540.00),
(54, 12, 12, '2026-06-13', '2026-06-17', 2, 'Concluída', 1680.00),
(55, 13, 19, '2026-06-16', '2026-06-21', 5, 'Cancelada', 2600.00),
(56, 14, 26, '2026-06-19', '2026-06-20', 1, 'Concluída', 1200.00),
(57, 15, 3, '2026-06-22', '2026-06-24', 2, 'Concluída', 360.00),
(58, 16, 10, '2026-06-25', '2026-06-28', 3, 'Concluída', 780.00),
(59, 17, 17, '2026-06-28', '2026-07-02', 4, 'Confirmada', 2080.00),
(60, 18, 24, '2026-07-01', '2026-07-06', 2, 'Concluída', 1750.00),
(61, 19, 1, '2026-07-04', '2026-07-05', 1, 'Confirmada', 180.00),
(62, 20, 8, '2026-07-07', '2026-07-09', 2, 'Cancelada', 520.00),
(63, 21, 15, '2026-07-10', '2026-07-13', 2, 'Concluída', 1260.00),
(64, 22, 22, '2026-07-13', '2026-07-17', 2, 'Concluída', 1400.00),
(65, 23, 29, '2026-07-16', '2026-07-21', 2, 'Hospedada', 2100.00),
(66, 24, 6, '2026-07-19', '2026-07-20', 1, 'Concluída', 260.00),
(67, 25, 13, '2026-07-22', '2026-07-24', 2, 'Concluída', 840.00),
(68, 26, 20, '2026-07-25', '2026-07-28', 3, 'Concluída', 1560.00),
(69, 27, 27, '2026-07-28', '2026-08-01', 4, 'Concluída', 4800.00),
(70, 28, 4, '2026-07-31', '2026-08-05', 2, 'Confirmada', 900.00),
(71, 29, 11, '2026-08-03', '2026-08-04', 1, 'Confirmada', 420.00),
(72, 30, 18, '2026-08-06', '2026-08-08', 2, 'Concluída', 1040.00),
(73, 31, 25, '2026-08-09', '2026-08-12', 2, 'Concluída', 1050.00),
(74, 32, 2, '2026-08-12', '2026-08-16', 2, 'Concluída', 720.00),
(75, 33, 9, '2026-08-15', '2026-08-20', 3, 'Hospedada', 1300.00),
(76, 34, 16, '2026-08-18', '2026-08-19', 1, 'Concluída', 520.00),
(77, 35, 23, '2026-08-21', '2026-08-23', 2, 'Hospedada', 700.00),
(78, 36, 30, '2026-08-24', '2026-08-27', 2, 'Cancelada', 1260.00),
(79, 37, 7, '2026-08-27', '2026-08-31', 3, 'Concluída', 1040.00),
(80, 38, 14, '2026-08-30', '2026-09-04', 2, 'Confirmada', 2100.00),
(81, 39, 21, '2026-09-02', '2026-09-03', 1, 'Confirmada', 350.00),
(82, 40, 28, '2026-09-05', '2026-09-07', 2, 'Concluída', 840.00),
(83, 41, 5, '2026-09-08', '2026-09-11', 2, 'Concluída', 540.00),
(84, 42, 12, '2026-09-11', '2026-09-15', 2, 'Confirmada', 1680.00),
(85, 1, 19, '2026-09-14', '2026-09-19', 5, 'Concluída', 2600.00),
(86, 2, 26, '2026-09-17', '2026-09-18', 1, 'Concluída', 1200.00),
(87, 3, 3, '2026-09-20', '2026-09-22', 2, 'Concluída', 360.00),
(88, 4, 10, '2026-09-23', '2026-09-26', 3, 'Hospedada', 780.00),
(89, 5, 17, '2026-09-26', '2026-09-30', 4, 'Cancelada', 2080.00),
(90, 6, 24, '2026-09-29', '2026-10-04', 2, 'Concluída', 1750.00),
(91, 7, 1, '2026-10-02', '2026-10-03', 1, 'Concluída', 180.00),
(92, 8, 8, '2026-10-05', '2026-10-07', 2, 'Concluída', 520.00),
(93, 9, 15, '2026-10-08', '2026-10-11', 2, 'Cancelada', 1260.00),
(94, 10, 22, '2026-10-11', '2026-10-15', 2, 'Cancelada', 1400.00),
(95, 11, 29, '2026-10-14', '2026-10-19', 2, 'Concluída', 2100.00),
(96, 12, 6, '2026-10-17', '2026-10-18', 1, 'Confirmada', 260.00),
(97, 13, 13, '2026-10-20', '2026-10-22', 2, 'Confirmada', 840.00),
(98, 14, 20, '2026-10-23', '2026-10-26', 3, 'Concluída', 1560.00),
(99, 15, 27, '2026-10-26', '2026-10-30', 4, 'Confirmada', 4800.00),
(100, 16, 4, '2026-10-29', '2026-11-03', 2, 'Concluída', 900.00),
(101, 17, 11, '2026-11-01', '2026-11-02', 1, 'Confirmada', 420.00),
(102, 18, 18, '2026-11-04', '2026-11-06', 2, 'Concluída', 1040.00),
(103, 19, 25, '2026-11-07', '2026-11-10', 2, 'Concluída', 1050.00),
(104, 20, 2, '2026-11-10', '2026-11-14', 2, 'Concluída', 720.00),
(105, 21, 9, '2026-01-07', '2026-01-12', 3, 'Concluída', 1300.00),
(106, 22, 16, '2026-01-10', '2026-01-11', 1, 'Hospedada', 520.00),
(107, 23, 23, '2026-01-13', '2026-01-15', 2, 'Cancelada', 700.00),
(108, 24, 30, '2026-01-16', '2026-01-19', 2, 'Cancelada', 1260.00),
(109, 25, 7, '2026-01-19', '2026-01-23', 3, 'Concluída', 1040.00),
(110, 26, 14, '2026-01-22', '2026-01-27', 2, 'Concluída', 2100.00),
(111, 27, 21, '2026-01-25', '2026-01-26', 1, 'Cancelada', 350.00),
(112, 28, 28, '2026-01-28', '2026-01-30', 2, 'Hospedada', 840.00),
(113, 29, 5, '2026-01-31', '2026-02-03', 2, 'Concluída', 540.00),
(114, 30, 12, '2026-02-03', '2026-02-07', 2, 'Concluída', 1680.00),
(115, 31, 19, '2026-02-06', '2026-02-11', 5, 'Concluída', 2600.00),
(116, 32, 26, '2026-02-09', '2026-02-10', 1, 'Confirmada', 1200.00),
(117, 33, 3, '2026-02-12', '2026-02-14', 2, 'Confirmada', 360.00),
(118, 34, 10, '2026-02-15', '2026-02-18', 3, 'Concluída', 780.00),
(119, 35, 17, '2026-02-18', '2026-02-22', 4, 'Concluída', 2080.00),
(120, 36, 24, '2026-02-21', '2026-02-26', 2, 'Concluída', 1750.00);

INSERT INTO funcionario
(id_funcionario, nome, cargo, salario, id_supervisor)
VALUES
(1, 'Marina Lopes', 'Gerente Geral', 9500.00, NULL),
(2, 'Paulo Mendes', 'Gerente de Hospedagem', 6800.00, 1),
(3, 'Renata Dias', 'Gerente de Operações', 7000.00, 1),
(4, 'Lucas Ferreira', 'Recepcionista', 3200.00, 2),
(5, 'Camila Barros', 'Recepcionista', 3300.00, 2),
(6, 'Rafael Moreira', 'Supervisor de Limpeza', 4100.00, 3),
(7, 'Bianca Freitas', 'Camareira', 2800.00, 6),
(8, 'Eduardo Tavares', 'Manutenção', 3500.00, 3),
(9, 'Aline Moraes', 'Atendimento', 3000.00, 2),
(10, 'Roberto Silva', 'Camareiro', 2750.00, 6);

-- Ajusta a sequência da identidade após inserções manuais com id_reserva.
SELECT setval(
    pg_get_serial_sequence('reserva', 'id_reserva'),
    (SELECT MAX(id_reserva) FROM reserva)
);
